module.exports = {
  /* APP */
  APP_URL: process.env.APP_URL ?? 'http://localhost:8080',
  API_URL: process.env.API_URL ?? 'http://localhost:3000',

  /* AZURE SERVICE */
  AZURE_STORAGE_SAS_KEY:
    process.env.AZURE_STORAGE_SAS_KEY ?? 'YOURAZURESTORAGEKEY',
  AZURE_STORAGE_ACCOUNT:
    process.env.AZURE_STORAGE_ACCOUNT ?? 'YOURAZURESTORAGEACCOUNT',

  /* DATABASE */
  MONGO_URI:
    process.env.MONGO_URI ?? 'mongodb://localhost:27017/YOURMONGODBNAME',

  /* AUTH SERVICE */
  WEBTOKEN_SECRET_KEY:
    process.env.WEBTOKEN_SECRET_KEY ?? 'YOURJWTSECRETCHANGEIT',
  WEBTOKEN_EXPIRATION_TIME: process.env.WEBTOKEN_EXPIRATION_TIME ?? '36000',
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID ?? 'YOURGOOGLECLIENTID',
  GOOGLE_SECRET: process.env.GOOGLE_SECRET ?? 'YOURGOOGLESECRET',
  AZURE_CLIENT_ID: process.env.AZURE_CLIENT_ID ?? 'YOURAZURECLIENTID',
  AZURE_SECRET: process.env.AZURE_SECRET ?? 'YOURAZURESECRET',
  AZURE_TENANT_ID: process.env.AZURE_TENANT_ID ?? 'YOURAZURETENANTID',
};
