name: API-TEST

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ci
      MONGO_URI: ${{ secrets.TEST_MONGO_URI }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'CI Testing'
        shell: bash
        run: |
          npm install
          cp config/default.js config/ci.js
          npm run test:e2e --if-present
          npm run test:cov --if-present
