name: API-TEST

on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      APP_URL: https://dsp-frontend.ap.ngrok.io
      API_URL: https://sf-dsp-mvp-api-dev.azurewebsites.net
      AZURE_STORAGE_SAS_KEY: ${{ secrets.CI_AZURE_STORAGE_SAS_KEY }}
      AZURE_STORAGE_ACCOUNT: ${{ secrets.CI_AZURE_STORAGE_ACCOUNT }}
      MONGO_URI: ${{ secrets.CI_MONGO_URI }}
      WEBTOKEN_SECRET_KEY: ${{ secrets.CI_WEBTOKEN_SECRET_KEY }}
      WEBTOKEN_EXPIRATION_TIME: ${{ secrets.CI_WEBTOKEN_EXPIRATION_TIME }}
      GOOGLE_CLIENT_ID: ${{ secrets.CI_GOOGLE_CLIENT_ID }}
      GOOGLE_SECRET: ${{ secrets.CI_GOOGLE_SECRET }}
      AZURE_CLIENT_ID: ${{ secrets.CI_AZURE_CLIENT_ID }}
      AZURE_SECRET: ${{ secrets.CI_AZURE_SECRET }}
      AZURE_TENANT: ${{ secrets.CI_AZURE_TENANT }}
      AZURE_TENANT_ID: ${{ secrets.CI_AZURE_TENANT_ID }}

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'CI Testing'
        shell: bash
        run: |
          npm install
          cp config/default.ts config/test.ts
          npm run test:e2e --if-present
          npm run test:cov --if-present
